'use client'
import { Inter } from "next/font/google";
import { useEffect, useState } from "react";
import "./globals.css";

import NavbarAdmin from "./components/admin_components/NavbarAdmin";
import NavbarClient from "./components/client_components/NavbarClient";
import NavbarDF from "./components/default_components/NavbarDF";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

function checkUserAuthentication() {
  const userType = sessionStorage.getItem("userType");
  console.log("root layout ka useeffect: ", userType)

  if (userType === "admin" || userType === "applicant") {
    return { type: userType };
  } else {
    return null;
  }
}

export default function RootLayout({ children }) {
  const [userType, setUserType] = useState("default");

  useEffect(() => {
    const storedUserType = checkUserAuthentication();
    if (storedUserType) {
      setUserType(storedUserType.type);
    }
  }, []);

  let NavbarComponent;
  if (userType === "admin") {
    NavbarComponent = NavbarAdmin;
  } else if (userType === "applicant") {
    NavbarComponent = NavbarClient;
  } else {
    NavbarComponent = NavbarDF;
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComponent>{children}</NavbarComponent>
      </body>
    </html>
  );
}
