import { Inter } from "next/font/google";
import "./globals.css";

// import Navbar from "./components/admin_components/NavbarAdmin";
// import Navbar from "./components/client_components/NavbarClient"
import Navbar from "./components/default_components/NavbarDF"

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar>{children}</Navbar>
        {/* <h1>HELLO THERE FORM LAYOUT</h1> */}
        {/* {children} */}
      </body>
    </html>
  );
}
